export { default as Figma } from './figma.png';
export { default as AdobeXD } from './adobe-xd.png';
export { default as Sketch } from './sketch.png';
export { default as Balsamiq } from './balsamiq-logo-screen.png';
export { default as Framer } from './framer.png';
export { default as DesignWithFramer } from './design-with-Framer.png';
export { default as HapticDesign } from './haptic-design.png';
export { default as Sampling } from './sampling.gif';
export { default as SolutionArchitecture } from './solution-architecture.png';
