export { default as CoverPage } from './CoverPage';
export { default as Agenda } from './Agenda';
export { default as Introduction } from './Introduction';
export { default as Goals } from './Goals';
export { default as UXDesign } from './UXDesign';
export { default as Implementation } from './Implementation';
export { default as Demostración } from './Demostration';
export { default as Conclusion } from './Conclusion';
export { default as Final } from './Final';
